server:
  port: 8080

spring:
  application:
    name: customer
  datasource:
    username: postgres
    password: filsalouna
    url: jdbc:postgresql://localhost:5432/customer
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
      show_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

clients:
  fraud:
    url: http://fraud-service-url

