server:
  port: 8080
spring:
  application:
    name: customer
  datasource:
    password: filsalouna
    url: jdbc:postgresql://postgres:5432/customer
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgresSQLDialect
        format_sql: true
    show_sql: true
  zipkin:
    base_url: http://zipkin:9411
  rabbitmq:
    addresses: rabbitmq:5672
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: false